channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.15

  # support multiple kernels in multiple conda envs
  - nb_conda_kernels=2.3.1

  # kerberos for HPC authentication
  # - krb5=1.19.3

  # used so that instructors can distribute their git files to students in jupyterhub
  - nbgitpuller=1.1.1

  # nbgrader and ngshare for instructors to create courses and grade assignments
  - nbgrader=0.8.1

  # scipy stack for general scientific computation
  - numpy=1.23.5
  - scipy=1.9.3
  - matplotlib=3.6.2
  - pandas=1.5.2
  - sympy=1.11.1

  # scale calculations for numpy/pandas/etc.
  - dask=2022.12.0

  # ipympl for matplotlib+jupyter integration
  - ipympl=0.9.2

  # some jupyter widgets
  # - ipyvolume
  - nglview=3.0.3
  - ipycytoscape=1.3.3
  - ipygany=0.5.0

  # scikits for machine learning and image processing
  - scikit-learn=1.2.0
  - scikit-image=0.19.3

  # color palettes for matplotlib
  - palettable=3.3.0

  # faster expression evaluator, jit compiler, and array functions for numpy
  - numexpr=2.8.3
  - numba=0.56.4
  - bottleneck=1.3.5

  # extending python and allowing it to interop with C for performance
  - cython=0.29.32

  # python wrapper for ipopt for nonlinear optimization
  - cyipopt=1.2.0

  # specify molecular structures in pandas
  - biopandas=0.4.1

  # molecular descriptor calculator
  - mordred=1.2.0

  # popular python library for astronomy
  # - astropy=5.2

  # python library for cartography
  # - cartopy=0.21.1

  # generic mapping tools
  - pygmt=0.7.0

  # python api for searching in the protein data bank
  - pypdb=2.2

  # spherical harmonics tools
  - pyshtools=4.10.1

  # package for parsing html
  - beautifulsoup4=4.11.1

  # packages for Max Rudolph's GEL240 class
  # - affine=2.3.1
  # - rasterio=1.3.4

  # use R from python
  # - rpy2 # NOTE not installing since this requires R version 3.6.x, not the 4.0.x we're installing

  # several common data visualization packages
  - seaborn=0.12.1
  - bokeh=2.4.3
  - bqplot=0.12.36

  # python/threejs binding for jupyter visualization
  - pythreejs=2.4.1

  # interactive leaflet maps in python
  - ipyleaflet=0.17.2

  # interactive webapps in python
  - dash=2.7.1

  # python to vega translator
  - vincent=0.4.4

  # common statistical model libraries
  - statsmodels=0.13.5
  - patsy=0.5.3

  # python data serialization
  - dill=0.3.6

  # HDF4 and HDF5 suport, common file formats for numerical data
  # and python packages to support them
  # - h5py=3.7.0
  # - pytables=3.7.0
  # - hdf4=4.2.15

  # read data from excel spreadsheets
  - xlrd=2.0.1

  # interactive learning material for mechanical vibrations
  - resonance=0.22.0

  # toolkit for multi-body dynamics
  - pydy=0.6.0

  # optimizing dynamic systems using direct collocation
  # - opty # NOTE not installing due to it only having packages for python up to 3.6. repackage?

  # common linear algebra library
  # highest version is 2.17, but it conflicts with xeus-cling
  - blas=2.116

  # octave kernel (octave itself installed through apt, see apt.txt for details
  - octave_kernel=0.35.1

  # R
  # NOTE: the conda build pack will autoinstall irkernel and rstudio
  # however, f**k dependency hell so we're helping it out a bit by installing irkernel and r-devtools here explicitly
  - r-essentials=4.2
  - r-irkernel=1.3.1
  - r-devtools=2.4.5

  # common package collection
  - r-tidyverse=1.3.2

  # make interactive maps in R
  - r-leaflet=2.1.1

  # univariate time series forecasts
  - r-forecast=8.19

  # create dashboards with shiny
  - r-shinydashboard=0.7.2

  # R interface for apache spark
  - r-sparklyr=1.7.9

  # simple features for spacial vector data
  - r-sf=1.0_7

  # nyc flights dataset
  - r-nycflights13=1.0.2

  # sqlite support in r
  - r-rsqlite=2.2.19

  # libcurl in r
  - r-rcurl=1.98_1.9

  # shiny gadget to create ggplot2 charts
  - r-esquisse=1.1.2

  # package manager for the bioconductor project
  - r-biocmanager=1.30.19

  # packages for Lindsay Poirier's class
  - r-rgdal=1.5_32
  - r-maptools=1.1_5

  # c++ kernel
  - xeus-cling=0.13.0

  # sagemath (kernel included)
  - sage=9.4

  # ipyparallel
  - ipyparallel=8.4.1

  # allow installation of pip packages
  - pip=22.3.1

  - pip:

    # visualization for ml datasets
    - facets-overview==1.0.0

    # package requested by Richard
    - diagrams==0.23.1

    # jupyter archive extension
    - jupyter-archive==3.3.3

    # jupyter git extension
    - jupyterlab-git==0.41.0

    # jupyterlab latex extension
    - jupyterlab_latex==3.1.0

    # ngshare for instructors to create courses and grade assignments
    - ngshare_exchange==0.5.3
