#!/bin/bash -e

# install some lab extensions

# add our FAQ to the help menu
jupyter labextension install git+https://github.com/LibreTexts/labextension-libretexts-faq --no-build

# finally, build the lab
jupyter lab build --dev-build=False

# create nbgrader_config to use ngshare as the exchange
# this allows nbgrader to be used on Z2JH
cat <<EOF > /srv/conda/envs/notebook/etc/jupyter/nbgrader_config.py
from ngshare_exchange import configureExchange
c=get_config()
configureExchange(c, 'http://ngshare:8080/services/ngshare')
c.CourseDirectory.course_id = '*'
EOF

# add ~/.conda/envs to the top of default env directories
# this way, newly created conda envs will be in ~
# which will get persisted
echo -e "envs_dirs:\n  - /home/$USER/.conda/envs" >> /srv/conda/.condarc
