#!/bin/bash -e

# add our FAQ to the help menu
# git clone https://github.com/LibreTexts/labextension-libretexts-faq.git
# cd labextension-libretexts-faq/
# jupyter labextension install .
# cd .. && rm -rf labextension-libretexts-faq/

# run to make sure all extensions are installed correctly
jupyter lab build

# create nbgrader_config to use ngshare as the exchange
# this allows nbgrader to be used on Z2JH
cat <<EOF > /srv/conda/envs/notebook/etc/jupyter/nbgrader_config.py
from ngshare_exchange import configureExchange
c=get_config()
configureExchange(c, 'http://ngshare:8080/services/ngshare')
c.CourseDirectory.course_id = '*'
EOF

# add ~/.conda/envs to the top of default env directories
# this way, newly created conda envs will be in ~
# which will get persisted
echo -e "envs_dirs:\n  - /home/$USER/.conda/envs" >> /srv/conda/.condarc
